import { Injectable, Logger } from '@nestjs/common';
import { FilesService } from '../../../../shared/files/files.service';
import { FilesRepository } from '../../infrastructure/files.repository';
import { FileUploadMetadataDto } from '../../api/dto/file-upload.dto';
import { FileEntity } from '../../domain/file.entity';

@Injectable()
export class UploadFileUseCase {
    private readonly logger = new Logger(UploadFileUseCase.name);

    constructor(
        private readonly storageService: FilesService,
        private readonly filesRepository: FilesRepository,
    ) { }

    async execute(file: Express.Multer.File, metadata: FileUploadMetadataDto, userId: string): Promise<FileEntity> {
        // 1. Upload to Storage
        const uploadResult = await this.storageService.uploadFile(file);

        // 2. Save Metadata to DB
        const fileRecord: FileEntity = {
            id: undefined, // Generated by DB
            fileName: file.originalname,
            filePath: uploadResult.url, // Store the URL/Path
            mimeType: uploadResult.mimeType,
            size: uploadResult.size,
            entityType: metadata.entityType,
            entityId: metadata.entityId,
            uploadedBy: userId,
            createdAt: new Date(),
        };

        const savedFile = await this.filesRepository.create(fileRecord);
        this.logger.log(`File uploaded: ${savedFile.id} (${savedFile.fileName})`);

        return savedFile;
    }
}
