export enum Permission {
  // Users
  USERS_READ = 'USERS_READ',
  USERS_CREATE = 'USERS_CREATE',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DELETE = 'USERS_DELETE',

  // Clients
  CLIENTS_READ = 'CLIENTS_READ',
  CLIENTS_CREATE = 'CLIENTS_CREATE',
  CLIENTS_UPDATE = 'CLIENTS_UPDATE',
  CLIENTS_DELETE = 'CLIENTS_DELETE',

  // Projects
  PROJECTS_READ = 'PROJECTS_READ',
  PROJECTS_CREATE = 'PROJECTS_CREATE',
  PROJECTS_UPDATE = 'PROJECTS_UPDATE',
  PROJECTS_DELETE = 'PROJECTS_DELETE',

  // Tasks
  TASKS_READ = 'TASKS_READ',
  TASKS_CREATE = 'TASKS_CREATE',
  TASKS_UPDATE = 'TASKS_UPDATE',
  TASKS_DELETE = 'TASKS_DELETE',

  // Time Tracking
  TIME_ENTRIES_READ = 'TIME_ENTRIES_READ',
  TIME_ENTRIES_CREATE = 'TIME_ENTRIES_CREATE',
  TIME_ENTRIES_UPDATE = 'TIME_ENTRIES_UPDATE',
  TIME_ENTRIES_DELETE = 'TIME_ENTRIES_DELETE',
  TIME_ENTRIES_APPROVE = 'TIME_ENTRIES_APPROVE',

  // Tickets
  TICKETS_READ = 'TICKETS_READ',
  TICKETS_CREATE = 'TICKETS_CREATE',
  TICKETS_UPDATE = 'TICKETS_UPDATE',
  TICKETS_DELETE = 'TICKETS_DELETE',

  // Invoices
  INVOICES_READ = 'INVOICES_READ',
  INVOICES_CREATE = 'INVOICES_CREATE',
  INVOICES_UPDATE = 'INVOICES_UPDATE',
  INVOICES_DELETE = 'INVOICES_DELETE',

  // Payments
  PAYMENTS_READ = 'PAYMENTS_READ',
  PAYMENTS_CREATE = 'PAYMENTS_CREATE',

  // Expenses
  EXPENSES_READ = 'EXPENSES_READ',
  EXPENSES_CREATE = 'EXPENSES_CREATE',
  EXPENSES_UPDATE = 'EXPENSES_UPDATE',
  EXPENSES_APPROVE = 'EXPENSES_APPROVE',

  // Contracts
  CONTRACTS_READ = 'CONTRACTS_READ',
  CONTRACTS_CREATE = 'CONTRACTS_CREATE',
  CONTRACTS_UPDATE = 'CONTRACTS_UPDATE',
  CONTRACTS_APPROVE = 'CONTRACTS_APPROVE',

  // Meetings
  MEETINGS_READ = 'MEETINGS_READ',
  MEETINGS_CREATE = 'MEETINGS_CREATE',
  MEETINGS_UPDATE = 'MEETINGS_UPDATE',
  MEETINGS_DELETE = 'MEETINGS_DELETE',

  // Files
  FILES_READ = 'FILES_READ',
  FILES_UPLOAD = 'FILES_UPLOAD',
  FILES_DELETE = 'FILES_DELETE',

  // Notifications
  NOTIFICATIONS_READ = 'NOTIFICATIONS_READ',

  // Audit
  AUDIT_READ = 'AUDIT_READ',
}
